# Just to let you know, this has mostly been ~stolen~ copied from https://github.com/CompactMods/CompactCrafting/blob/1.16.x/.github/workflows/tagged-release.yml
# Why? Just because I'm lazy, that's about it.
name: Latest tag

on:
  push:
    tags:
    - v6*
  workflow_dispatch:

jobs:
  build:
    name: Build Jars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Publish JAR with Gradle
        run: ./gradlew build
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Jars
        uses: actions/upload-artifact@v3
        with:
          name: libs
          path: build/libs/*.jar

  publishRelease:
    name: Make Releases
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Download Build Results
        uses: actions/download-artifact@v3
        with:
          name: libs
          path: build/libs

      - name: Get TAG
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: "Release ${{ env.RELEASE_VERSION }}"
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: build/libs/*.jar
